[package]
name = "json_keys_case_changer"
version = "0.1.0"
authors = ["David Camperos <camperos.davidjosue@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = { version = "1.0.56", features = ["preserve_order"] }
convert_case = "0.4.0"
